// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkvbrnrqswqdlinfexeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrdmJybnJxc3dxZGxpbmZleGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMTk1MDcsImV4cCI6MjA2MDg5NTUwN30.4GjpVJXCeh3nWM5ut8yPAYZtm7duueK6JvxjWQj9QhU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);